#!/bin/csh

# run all ABC problems

set date = "10Sept08"

ccell_g++ < in.abc.ode
mv log.ccell log.abc.ode.$date

ccell_g++ < in.abc.gillespie
mv log.ccell log.abc.gillespie.$date

ccell_g++ < in.abc.spatial.box
mv log.ccell log.abc.spatial.box.$date.1

mpirun -np 4 ccell_g++ < in.abc.spatial.box
mv log.ccell log.abc.spatial.box.$date.4

ccell_g++ < in.abc.spatial.sphere
mv log.ccell log.abc.spatial.sphere.$date

ccell_g++ < in.abc.smoldyn
mv log.ccell log.abc.smoldyn.$date

