# liberty = Institutional Cluster, HP with dual Xeon CPUs

SHELL = /bin/sh
.IGNORE:

# System-specific settings

CC =		mpiCC
CCFLAGS =	-O -I/home/sjplimp/zoltan/Zoltan/include
DEPFLAGS =	-M
LINK =		mpiCC
LINKFLAGS =	-O -L/home/sjplimp/zoltan/Zoltan/Obj_icc
USRLIB =	-lzoltan -lzoltan_mem -lzoltan_comm
SYSLIB =	-lm
SIZE =		size

# Link rule

$(EXE):	$(OBJ)
	$(LINK) $(LINKFLAGS) $(OBJ) $(USRLIB) $(SYSLIB) -o $(EXE)
	$(SIZE) $(EXE)

# Compilation rules

%.o:%.cpp
	$(CC) $(CCFLAGS) -c $<

%.d:%.cpp
	$(CC) $(CCFLAGS) $(DEPFLAGS) $< > $@

# Individual dependencies

DEPENDS = $(OBJ:.o=.d)
include $(DEPENDS)
